// Mocks generated by Mockito 5.4.6 from annotations
// in lightning_meet_fe/test/providers/meeting_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:lightning_meet_fe/data/models/meeting_model.dart' as _i3;
import 'package:lightning_meet_fe/data/models/page_response_model.dart' as _i2;
import 'package:lightning_meet_fe/data/services/meeting_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePageResponse_0<T> extends _i1.SmartFake
    implements _i2.PageResponse<T> {
  _FakePageResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMeeting_1 extends _i1.SmartFake implements _i3.Meeting {
  _FakeMeeting_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MeetingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeetingService extends _i1.Mock implements _i4.MeetingService {
  MockMeetingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.PageResponse<_i3.Meeting>> getMeetings({
    int? page = 0,
    int? size = 10,
    String? region,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMeetings, [], {
              #page: page,
              #size: size,
              #region: region,
            }),
            returnValue: _i5.Future<_i2.PageResponse<_i3.Meeting>>.value(
              _FakePageResponse_0<_i3.Meeting>(
                this,
                Invocation.method(#getMeetings, [], {
                  #page: page,
                  #size: size,
                  #region: region,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.PageResponse<_i3.Meeting>>);

  @override
  _i5.Future<_i3.Meeting> getMeetingDetail(int? meetingId) =>
      (super.noSuchMethod(
            Invocation.method(#getMeetingDetail, [meetingId]),
            returnValue: _i5.Future<_i3.Meeting>.value(
              _FakeMeeting_1(
                this,
                Invocation.method(#getMeetingDetail, [meetingId]),
              ),
            ),
          )
          as _i5.Future<_i3.Meeting>);

  @override
  _i5.Future<void> createMeeting({
    required String? title,
    required String? content,
    required String? region,
    required String? location,
    String? keywords,
    required int? maxParticipants,
    required DateTime? time,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createMeeting, [], {
              #title: title,
              #content: content,
              #region: region,
              #location: location,
              #keywords: keywords,
              #maxParticipants: maxParticipants,
              #time: time,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.Meeting>> getImminentMeetings() =>
      (super.noSuchMethod(
            Invocation.method(#getImminentMeetings, []),
            returnValue: _i5.Future<List<_i3.Meeting>>.value(<_i3.Meeting>[]),
          )
          as _i5.Future<List<_i3.Meeting>>);

  @override
  _i5.Future<void> updateMeeting({
    required int? meetingId,
    String? title,
    String? content,
    String? region,
    String? location,
    String? keywords,
    int? maxParticipants,
    DateTime? time,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateMeeting, [], {
              #meetingId: meetingId,
              #title: title,
              #content: content,
              #region: region,
              #location: location,
              #keywords: keywords,
              #maxParticipants: maxParticipants,
              #time: time,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> joinMeeting(int? meetingId) =>
      (super.noSuchMethod(
            Invocation.method(#joinMeeting, [meetingId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> leaveMeeting(int? meetingId) =>
      (super.noSuchMethod(
            Invocation.method(#leaveMeeting, [meetingId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.Meeting>> getMyCreatedMeetings() =>
      (super.noSuchMethod(
            Invocation.method(#getMyCreatedMeetings, []),
            returnValue: _i5.Future<List<_i3.Meeting>>.value(<_i3.Meeting>[]),
          )
          as _i5.Future<List<_i3.Meeting>>);

  @override
  _i5.Future<List<_i3.Meeting>> getMyParticipatingMeetings() =>
      (super.noSuchMethod(
            Invocation.method(#getMyParticipatingMeetings, []),
            returnValue: _i5.Future<List<_i3.Meeting>>.value(<_i3.Meeting>[]),
          )
          as _i5.Future<List<_i3.Meeting>>);
}
